import AuthProvider from "@/components/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import { StoreProvider } from "@/store/StoreProvider";
import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <StoreProvider>
      <html lang="en" className={`${GeistSans.variable}`}>
        <AuthProvider>
          <body>
            {children}
            <Toaster />
          </body>
        </AuthProvider>
      </html>
    </StoreProvider>
  );
}
